# Generated by Django 5.1.4 on 2024-12-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='foto_principal',
            field=models.ImageField(blank=True, null=True, upload_to='carros/'),
        ),
    ]
